spring:
  security:
    user:
      name: guest
      password: guest123
    oauth2:
      client:
        clientId: trustedClient
        clientSecret: trustedClient123
        authorized-grant-types: authorization_code, refresh_token, password
        scope: openid
bootrest:
  customproperty: Testje